## 1. CHOPCHOP

### obtain the sgrna

In [1]:
import os
import itertools
import subprocess

import pandas as pd

In [2]:
def clean_path(directory, extension):
    for filename in os.listdir(directory):
        file_path = os.path.join(directory, filename)
        if os.path.isfile(file_path):
            if not filename.endswith(extension):
                os.remove(file_path)

In [3]:
cmd = f"-J -BED -G hg38 -filterGCmin 30 -filterGCmax 70 -t WHOLE -n N -R 4 " + \
       "-3 PRODUCT_SIZE_MIN=150,PRODUCT_SIZE_MAX=290,PRIMER_MIN_SIZE=18,PRIMER_MAX_SIZE=25,PRIMER_OPT_SIZE=22,PRIMER_MIN_TM=57,PRIMER_MAX_TM=63,PRIMER_OPT_TM=60 " + \
       "-A 290 -DF 300 -a 20 -T 1 -g 20 -scoringMethod DOENCH_2014 -f NN -v 3 -M NGG -BB AGGCTAGTCCGT"

cmd_user   = " ".join( [f"--targets chr11:5290000-5292000 -o ./result",cmd] )

In [4]:
os.makedirs('./result', exist_ok=True)

with open('./result/_result_.tsv', 'w') as f:
    subprocess.run(
        ["python", "./chopchop/chopchop_py3.py"] + cmd_user.split(),
        stdout=f,
        text=True
    )
clean_path('./result','.tsv')

./chopchop/chopchop_py3.py:2770: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if e_id is not -1:
./chopchop/chopchop_py3.py:2989: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if tx_start is not -1:
./chopchop/chopchop_py3.py:1250: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  sam = pandas.read_csv(bowtieResultsFile, sep='\t', names=list(range(14)),

In [5]:
table = pd.read_csv(f'./result/_result_.tsv',sep='\t',skiprows=1)
table = table[(table['MM0']==0) & (table['MM1']<=1)].reset_index(drop=True)
table[['chr','start']] = table['Genomic location'].str.split(':',expand=True).values
table['start'] = table['start'].astype(int);table['end'] = table['start']+23
table.head(n=10)

,Rank,Target sequence,Genomic location,Strand,GC content (%),Self-complementarity,MM0,MM1,MM2,MM3,Efficiency,chr,start,end
0,1,TCGTCATAATATGGGTTTTATGG,chr11:5291785,-,30,0,0,0,0,1,0.02,chr11,5291785,5291808
1,2,AGTTTAGGCTAGTAAGCATGAGG,chr11:5291658,-,40,4,0,0,0,3,0.41,chr11,5291658,5291681
2,3,CTGCTGTTATGACCACTAGAGGG,chr11:5291438,-,45,1,0,0,0,4,0.78,chr11,5291438,5291461
3,4,GAGTCTTGCAGGGTAGTGTAGGG,chr11:5290281,-,50,0,0,0,0,4,0.34,chr11,5290281,5290304
4,5,CGTGAAGCACGTCCAAGTGAAGG,chr11:5291862,+,55,1,0,0,0,4,0.34,chr11,5291862,5291885
5,6,CAATAGGGTCATGTTCAGTAGGG,chr11:5290409,+,40,0,0,0,0,4,0.32,chr11,5290409,5290432
6,7,ACGTAGTCTGTGCTTATGACTGG,chr11:5291842,-,45,2,0,0,0,4,0.20,chr11,5291842,5291865
7,8,ACAATAGGGTCATGTTCAGTAGG,chr11:5290408,+,40,0,0,0,0,4,0.03,chr11,5290408,5290431
8,9,CAAGGTACTTTGGTCTGGACAGG,chr11:5290032,+,50,0,0,0,1,3,0.05,chr11,5290032,5290055
9,10,GATGTCCTGTCCCTGTAAGGTGG,chr11:5291324,+,55,0,0,0,0,5,0.39,chr11,5291324,5291347

In [6]:
permutations = list(itertools.permutations(table.index, 2))
pair_df = pd.DataFrame({
    'chr':           [table.loc[i, 'chr'] for i, j in permutations],
    'Cutsite_1':     [table.loc[i, 'start'] for i, j in permutations],
    'Cutsite_2':     [table.loc[j, 'start'] for i, j in permutations],
    'seq1':          [table.loc[i, 'Target sequence'] for i, j in permutations],
    'seq2':          [table.loc[j, 'Target sequence'] for i, j in permutations],
})
pair_df['pair_length'] = pair_df['Cutsite_2'].astype(int) - pair_df['Cutsite_1'].astype(int)
pair_df_filtered = pair_df[(pair_df['pair_length'] >= 50) & (pair_df['pair_length'] <= 200)].reset_index(drop=True)
pair_df_filtered.columns=['chr','start','end','seq1','seq2','length']
pair_df_filtered.head(n=10)

,chr,start,end,seq1,seq2,length
0,chr11,5291785,5291862,TCGTCATAATATGGGTTTTATGG,CGTGAAGCACGTCCAAGTGAAGG,77
1,chr11,5291785,5291842,TCGTCATAATATGGGTTTTATGG,ACGTAGTCTGTGCTTATGACTGG,57
2,chr11,5291785,5291866,TCGTCATAATATGGGTTTTATGG,AAGCACGTCCAAGTGAAGGCAGG,81
3,chr11,5291785,5291985,TCGTCATAATATGGGTTTTATGG,ACAGATAACTCTGCTAATAAAGG,200
4,chr11,5291785,5291916,TCGTCATAATATGGGTTTTATGG,TTCTGCTATTCTTGATCAAATGG,131
5,chr11,5291785,5291977,TCGTCATAATATGGGTTTTATGG,AGCAGAGTTATCTGTACTGTTGG,192
6,chr11,5291785,5291921,TCGTCATAATATGGGTTTTATGG,TGATCAAGAATAGCAGAAAAAGG,136
7,chr11,5291785,5291874,TCGTCATAATATGGGTTTTATGG,TCATTTCTCCTGCCTTCACTTGG,89
8,chr11,5291785,5291878,TCGTCATAATATGGGTTTTATGG,GTGAAGGCAGGAGAAATGAGAGG,93
9,chr11,5291785,5291891,TCGTCATAATATGGGTTTTATGG,AAATGAGAGGAGCAAGAAAGAGG,106

###

## 2. Sequence alignments & Epigenomic feature

In [7]:
import numpy as np
import pandas as pd

import pyBigWig
from pyfaidx import Fasta

In [8]:
trans_base_dict={'A':'T','C':'G','G':'C','T':'A','N':'N'}
chr_list = [f'chr{i}' for i in range(1,23)]+['chrX']

def reverse_DNA(seq):
    ### 用于反转DNA
    return ''.join([trans_base_dict[c] for c in seq])[::-1]

def gc_content(seq_list):
    ### 计算GC含量
    content = []
    for seq in seq_list:
        if len(seq)==0:
            content.append(0.0)
        else:
            content.append( (seq.upper().count('C')+seq.upper().count('G')) / len(seq) )
    return content

def find_contextual_single(data,fa=None,col_name = 'sequence',expand_flank=30,upstream=4,spacer_len=20,downstream=6):
    
    # 自动寻找上下文并且把补全上下文之后的序列整理成有30bp的格式
    ## 因为参考基因组并不会随着细胞系的改变而改变，所以这里可以这么做

    p1,p2=[],[];e1,e2=[],[]
    adj_s1,adj_s2=[],[]
    merge_table=data
    
    for _,row in merge_table.iterrows():
    
        s1 = row[col_name].upper().replace(' ','') # 因为输出是ChopChop的,非常稳定，就是20 bp protospacer + 3 bp PAM

        try:
            c,s,e = row['chr'],int(row['start']),int(row['end'])
            if not c in chr_list:
                p1.append('-1');e1.append('N'*total_len);adj_s1.append(-1)
                continue
        except:
            p1.append('-1');e1.append('N'*upstream+s1+'N'*downstream);adj_s1.append(-1)
            continue

        sequence=fa[c][s-expand_flank:e+expand_flank].seq.upper()

        l1=sequence.find(s1)

        if l1<0: # 没有抓取到位置信息的情况,自动认为是负向的
            l1=sequence.find(reverse_DNA(s1))
            p1.append('0');e1.append( reverse_DNA( fa[c][s-expand_flank+l1-downstream:s-expand_flank+l1+spacer_len+upstream].seq.upper() ) )
        else:
            p1.append('1');e1.append( fa[c][s-expand_flank+l1-upstream:s-expand_flank+l1+spacer_len+downstream].seq.upper() )
        adj_s1.append(s-expand_flank+l1)
    
    return p1,e1,adj_s1

def gain_epivalue_TPM(region,bw=None):
    
    chromo=region[0]
    start=min(region[1],region[2])
    end=max(region[1],region[2])
    
    if start==end:
        end+=1
        
    delta=end-start
    
    try:
        values = bw.stats(chromo, start, end, type='sum')[0]
        tpm = (values/delta)/(bw.header()['sumData']/bw.header()['nBasesCovered'])*1000
    except Exception as e:
        tpm = 0
    return tpm

def gain_series_TPM(data,epi='DNase',cellline='A549',genome='hg38',lo=None):
    
    epi_value_series=[]
    
    if genome=='hg38': 
        bw=pyBigWig.open(f"epigenome_ref/{cellline}/{epi}.bigWig")
    elif genome=='hg19':
        bw=pyBigWig.open(f"epigenome_ref/{cellline}/hg19/{epi}.bigWig")
    
    for i in range(len(data)):
        c,s,e = data.at[i,'chr'],data.at[i,'start'],data.at[i,'end']
        if s==e:
            e+=1
        else:
            s,e = min(s,e),max(s,e)
        if not lo is None:
            c,s,e = convert_loci([c,s,e],lo=lo)
        
        try:
            epi_value_series.append(gain_epivalue_TPM([c,s,e],bw=bw))
        except:
            epi_value_series.append(0.0)
    
    bw.close()
    
    return epi_value_series

In [9]:
test_data = pair_df_filtered.copy()

In [10]:
test_data.head(n=10)

,chr,start,end,seq1,seq2,length
0,chr11,5291785,5291862,TCGTCATAATATGGGTTTTATGG,CGTGAAGCACGTCCAAGTGAAGG,77
1,chr11,5291785,5291842,TCGTCATAATATGGGTTTTATGG,ACGTAGTCTGTGCTTATGACTGG,57
2,chr11,5291785,5291866,TCGTCATAATATGGGTTTTATGG,AAGCACGTCCAAGTGAAGGCAGG,81
3,chr11,5291785,5291985,TCGTCATAATATGGGTTTTATGG,ACAGATAACTCTGCTAATAAAGG,200
4,chr11,5291785,5291916,TCGTCATAATATGGGTTTTATGG,TTCTGCTATTCTTGATCAAATGG,131
5,chr11,5291785,5291977,TCGTCATAATATGGGTTTTATGG,AGCAGAGTTATCTGTACTGTTGG,192
6,chr11,5291785,5291921,TCGTCATAATATGGGTTTTATGG,TGATCAAGAATAGCAGAAAAAGG,136
7,chr11,5291785,5291874,TCGTCATAATATGGGTTTTATGG,TCATTTCTCCTGCCTTCACTTGG,89
8,chr11,5291785,5291878,TCGTCATAATATGGGTTTTATGG,GTGAAGGCAGGAGAAATGAGAGG,93
9,chr11,5291785,5291891,TCGTCATAATATGGGTTTTATGG,AAATGAGAGGAGCAAGAAAGAGG,106

In [11]:
with Fasta("genome_ref/hg38.fa") as hg38:
    _,test_data['seq1'],_ = find_contextual_single(test_data,col_name='seq1',fa=hg38,upstream=4,spacer_len=23,downstream=3)
    _,test_data['seq2'],_ = find_contextual_single(test_data,col_name='seq2',fa=hg38,upstream=4,spacer_len=23,downstream=3)
    test_data['Median_sequence']=test_data.apply( lambda x: hg38[x['chr']][ x['start']:x['end'] ].seq.upper() , axis=1 )
test_data['GC']=gc_content(test_data['Median_sequence'])
test_data['length'] = abs(test_data['end'] - test_data['start'])

In [12]:
test_data

,chr,start,end,seq1,seq2,length,Median_sequence,GC
0,chr11,5291785,5291862,TTGTTCGTCATAATATGGGTTTTATGGTCC,ACTACGTGAAGCACGTCCAAGTGAAGGCAG,77,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.324675
1,chr11,5291785,5291842,TTGTTCGTCATAATATGGGTTTTATGGTCC,CTTCACGTAGTCTGTGCTTATGACTGGATT,57,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.280702
2,chr11,5291785,5291866,TTGTTCGTCATAATATGGGTTTTATGGTCC,CGTGAAGCACGTCCAAGTGAAGGCAGGAGA,81,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.333333
3,chr11,5291785,5291985,TTGTTCGTCATAATATGGGTTTTATGGTCC,CAGTACAGATAACTCTGCTAATAAAGGTAG,200,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.380000
4,chr11,5291785,5291916,TTGTTCGTCATAATATGGGTTTTATGGTCC,CTTTTTCTGCTATTCTTGATCAAATGGCTC,131,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.404580
...,...,...,...,...,...,...,...,...
974,chr11,5290980,5291030,TCTGAGAAATGAGAGAGAGAAATGGGGAGG,GTAAGAGACAGGGAAGGAGGTGTGGGGAAA,50,GAAATGAGAGAGAGAAATGGGGAGGGTAGAAGGAAGGAAGATAGGG...,0.460000
975,chr11,5291023,5291184,AGATAGGGTAAGAGACAGGGAAGGAGGTGT,AGTCTATGGCATTTTCAAAATGCAAGGTGA,161,GGGTAAGAGACAGGGAAGGAGGTGTGGGGAAAGAAATTAAATTATT...,0.354037
976,chr11,5291023,5291127,AGATAGGGTAAGAGACAGGGAAGGAGGTGT,TTCTTTATTTCAAGAGTCCAGAAATGGCAA,104,GGGTAAGAGACAGGGAAGGAGGTGTGGGGAAAGAAATTAAATTATT...,0.384615
977,chr11,5291003,5291184,GGGGAGGGTAGAAGGAAGGAAGATAGGGTA,AGTCTATGGCATTTTCAAAATGCAAGGTGA,181,GGGTAGAAGGAAGGAAGATAGGGTAAGAGACAGGGAAGGAGGTGTG...,0.364641
978,chr11,5291003,5291127,GGGGAGGGTAGAAGGAAGGAAGATAGGGTA,TTCTTTATTTCAAGAGTCCAGAAATGGCAA,124,GGGTAGAAGGAAGGAAGATAGGGTAAGAGACAGGGAAGGAGGTGTG...,0.395161

In [13]:
test_data['DNase']=gain_series_TPM( test_data, epi='DNase'  , cellline='K562', genome='hg38', lo=None)
test_data['ATAC'] =gain_series_TPM( test_data, epi='ATAC'   , cellline='K562', genome='hg38', lo=None)
test_data['H3K27ac']=gain_series_TPM( test_data, epi='H3K27ac', cellline='K562', genome='hg38', lo=None)
test_data['H3K4me3']=gain_series_TPM( test_data, epi='H3K4me3', cellline='K562', genome='hg38', lo=None)

In [14]:
test_data.head(n=10)

,chr,start,end,seq1,seq2,length,Median_sequence,GC,DNase,ATAC,H3K27ac,H3K4me3
0,chr11,5291785,5291862,TTGTTCGTCATAATATGGGTTTTATGGTCC,ACTACGTGAAGCACGTCCAAGTGAAGGCAG,77,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.324675,2655.160358,1439.819021,8201.426667,1548.616286
1,chr11,5291785,5291842,TTGTTCGTCATAATATGGGTTTTATGGTCC,CTTCACGTAGTCTGTGCTTATGACTGGATT,57,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.280702,2516.186811,1324.025582,7605.602229,1490.280470
2,chr11,5291785,5291866,TTGTTCGTCATAATATGGGTTTTATGGTCC,CGTGAAGCACGTCCAAGTGAAGGCAGGAGA,81,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.333333,2677.603396,1455.984184,8308.198716,1563.625589
3,chr11,5291785,5291985,TTGTTCGTCATAATATGGGTTTTATGGTCC,CAGTACAGATAACTCTGCTAATAAAGGTAG,200,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.380000,2768.006239,1565.290943,9461.169541,1368.764784
4,chr11,5291785,5291916,TTGTTCGTCATAATATGGGTTTTATGGTCC,CTTTTTCTGCTATTCTTGATCAAATGGCTC,131,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.404580,2908.694988,1641.233277,9051.396525,1550.709719
5,chr11,5291785,5291977,TTGTTCGTCATAATATGGGTTTTATGGTCC,TATTAGCAGAGTTATCTGTACTGTTGGCAT,192,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.380208,2798.177882,1591.162930,9484.503885,1398.947536
6,chr11,5291785,5291921,TTGTTCGTCATAATATGGGTTTTATGGTCC,CATTTGATCAAGAATAGCAGAAAAAGGAAA,136,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.397059,2919.839088,1657.720258,9140.680662,1541.707365
7,chr11,5291785,5291874,TTGTTCGTCATAATATGGGTTTTATGGTCC,CCTCTCATTTCTCCTGCCTTCACTTGGACG,89,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.359551,2720.374678,1489.370317,8477.729842,1586.816715
8,chr11,5291785,5291878,TTGTTCGTCATAATATGGGTTTTATGGTCC,CCAAGTGAAGGCAGGAGAAATGAGAGGAGC,93,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.365591,2739.000882,1508.226901,8540.033365,1594.701282
9,chr11,5291785,5291891,TTGTTCGTCATAATATGGGTTTTATGGTCC,GGAGAAATGAGAGGAGCAAGAAAGAGGAGC,106,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.386792,2806.353851,1561.282080,8739.053723,1589.887169

## Single Guide Prediction

In [15]:
import ctypes
ctypes.cdll.LoadLibrary('lib/libcudart.so.12')
ctypes.cdll.LoadLibrary('lib/libnvJitLink.so.12')

In [16]:
import torch
import tensorflow as tf

import utils.DeepSpCas9_main as DeepSpCas9
import utils.DeepCRISPR_main as DeepCRISPR
import utils.DistillatedRuleSet2 as Ruleset2
import utils.DistillatedCRISPRedict as CRISPRedict

WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.

2025-10-19 13:30:58.541627: I tensorflow/stream_executor/platform/default/dso_loader.cc:50] Successfully opened dynamic library libcudart.so.12
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.

TensorFlow version: 1.15.5
Running in TensorFlow 1.x compatibility mode.
WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/conda/env/cp38tf1/lib/python3.8/site-packages/sonnet/python/modules/util.py:57: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/conda/env/cp38tf1/lib/python3.8/site-packages/sonnet/python/modules/util.py:57: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

In [17]:
test_data['DeepSpCas9_s1'] = DeepSpCas9.predict_sequence(test_data['seq1'])
test_data['DeepSpCas9_s2'] = DeepSpCas9.predict_sequence(test_data['seq2'])
test_data['DeepCRISPR_s1'] = DeepCRISPR.predict_sequence([seq[4:27] for seq in test_data['seq1']], model_path='DeepCRISPR_Seq/')
test_data['DeepCRISPR_s2'] = DeepCRISPR.predict_sequence([seq[4:27] for seq in test_data['seq2']], model_path='DeepCRISPR_Seq/')
test_data['Ruleset2_s1']   = Ruleset2.predict(test_data['seq1'],model_path='models/DistillatedRuleSet2.pth')
test_data['Ruleset2_s2']   = Ruleset2.predict(test_data['seq2'],model_path='models/DistillatedRuleSet2.pth')
test_data['CRISPRedit_s1'] = CRISPRedict.predict(test_data['seq1'],model_path='models/DistillatedCRISPRedict.pth')
test_data['CRISPRedit_s2'] = CRISPRedict.predict(test_data['seq2'],model_path='models/DistillatedCRISPRedict.pth')

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:195: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:195: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:214: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:214: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:215: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:215: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:216: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

2025-10-19 13:31:19.217881: I tensorflow/core/platform/profile_utils/cpu_utils.cc:109] CPU Frequency: 2700000000 Hz
2025-10-19 13:31:19.233193: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7efdd5c36160 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2025-10-19 13:31:19.233230: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2025-10-19 13:31:19.235337: I tensorflow/stream_executor/platform/default/dso_loader.cc:50] Successfully opened dynamic library libcuda.so.1
2025-10-19 13:31:19.308350: E tensorflow/stream_executor/cuda/cuda_driver.cc:282] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2025-10-19 13:31:19.308447: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node1): /proc/driver/nvidia/version does not exist
WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:216: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:40: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:40: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:50: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:50: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:66: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:66: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:74: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:74: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:86: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:86: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:106: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:106: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:219: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepSpCas9_main.py:219: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

INFO:tensorflow:Restoring parameters from ./DeepCas9_Final/PreTrain-Final-False-3-5-7-100-70-40-0.001-550-True-80-60

INFO:tensorflow:Restoring parameters from ./DeepCas9_Final/PreTrain-Final-False-3-5-7-100-70-40-0.001-550-True-80-60

INFO:tensorflow:Restoring parameters from ./DeepCas9_Final/PreTrain-Final-False-3-5-7-100-70-40-0.001-550-True-80-60

INFO:tensorflow:Restoring parameters from ./DeepCas9_Final/PreTrain-Final-False-3-5-7-100-70-40-0.001-550-True-80-60

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepCRISPR_main.py:53: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/utils/DeepCRISPR_main.py:53: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/conda/env/cp38tf1/lib/python3.8/site-packages/sonnet/python/modules/base.py:171: The name tf.make_template is deprecated. Please use tf.compat.v1.make_template instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/conda/env/cp38tf1/lib/python3.8/site-packages/sonnet/python/modules/base.py:171: The name tf.make_template is deprecated. Please use tf.compat.v1.make_template instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/conda/env/cp38tf1/lib/python3.8/site-packages/sonnet/python/modules/base.py:239: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/conda/env/cp38tf1/lib/python3.8/site-packages/sonnet/python/modules/base.py:239: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/DeepCRISPR_Seq/deepcrispr_src.py:10: The name tf.local_variables_initializer is deprecated. Please use tf.compat.v1.local_variables_initializer instead.

WARNING:tensorflow:From /cluster/huanglab/sluo/sluoo/DeepDC_test_git/DeepDC/DeepCRISPR_Seq/deepcrispr_src.py:10: The name tf.local_variables_initializer is deprecated. Please use tf.compat.v1.local_variables_initializer instead.

DeepCRISPR_Seq/model.ckpt-seq loaded
DeepCRISPR_Seq/model.ckpt-seq loaded

In [18]:
def norm(x):
    return (x-x.min())/(x.max()-x.min())

if not test_data['DeepSpCas9_s1'].max() - test_data['DeepSpCas9_s1'].min() == 0:
    test_data['DeepSpCas9_s1'] = norm(test_data['DeepSpCas9_s1'])*10
if not test_data['DeepSpCas9_s2'].max() - test_data['DeepSpCas9_s2'].min() == 0:
    test_data['DeepSpCas9_s2'] = norm(test_data['DeepSpCas9_s2'])*10
    
if not test_data['DeepCRISPR_s1'].max() - test_data['DeepCRISPR_s1'].min() == 0:
    test_data['DeepSpCas9_s1'] = norm(test_data['DeepCRISPR_s1'])*10
if not test_data['DeepCRISPR_s2'].max() - test_data['DeepCRISPR_s2'].min() == 0:
    test_data['DeepSpCas9_s2'] = norm(test_data['DeepCRISPR_s2'])*10

if not test_data['CRISPRedit_s1'].max() - test_data['CRISPRedit_s1'].min() == 0:
    test_data['CRISPRedit_s1'] = norm(test_data['CRISPRedit_s1'])*10
if not test_data['CRISPRedit_s2'].max() - test_data['CRISPRedit_s2'].min() == 0:
    test_data['CRISPRedit_s2'] = norm(test_data['CRISPRedit_s2'])*10

if not test_data['Ruleset2_s1'].max() - test_data['Ruleset2_s1'].min() == 0:
    test_data['Ruleset2_s1'] = norm(test_data['Ruleset2_s1'])*10
if not test_data['Ruleset2_s2'].max() - test_data['Ruleset2_s2'].min() == 0:
    test_data['Ruleset2_s2'] = norm(test_data['Ruleset2_s2'])*10

In [19]:
test_data.head(n=10)

,chr,start,end,seq1,seq2,length,Median_sequence,GC,DNase,ATAC,H3K27ac,H3K4me3,DeepSpCas9_s1,DeepSpCas9_s2,DeepCRISPR_s1,DeepCRISPR_s2,Ruleset2_s1,Ruleset2_s2,CRISPRedit_s1,CRISPRedit_s2
0,chr11,5291785,5291862,TTGTTCGTCATAATATGGGTTTTATGGTCC,ACTACGTGAAGCACGTCCAAGTGAAGGCAG,77,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.324675,2655.160358,1439.819021,8201.426667,1548.616286,0.310717,1.422462,0.095022,0.143088,4.436039,4.864209,1.501069,6.430655
1,chr11,5291785,5291842,TTGTTCGTCATAATATGGGTTTTATGGTCC,CTTCACGTAGTCTGTGCTTATGACTGGATT,57,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.280702,2516.186811,1324.025582,7605.602229,1490.280470,0.310717,2.546439,0.095022,0.191683,4.436039,5.162989,1.501069,4.566238
2,chr11,5291785,5291866,TTGTTCGTCATAATATGGGTTTTATGGTCC,CGTGAAGCACGTCCAAGTGAAGGCAGGAGA,81,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.333333,2677.603396,1455.984184,8308.198716,1563.625589,0.310717,2.781013,0.095022,0.201825,4.436039,2.715565,1.501069,6.432423
3,chr11,5291785,5291985,TTGTTCGTCATAATATGGGTTTTATGGTCC,CAGTACAGATAACTCTGCTAATAAAGGTAG,200,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.380000,2768.006239,1565.290943,9461.169541,1368.764784,0.310717,2.267465,0.095022,0.179622,4.436039,8.376158,1.501069,4.279911
4,chr11,5291785,5291916,TTGTTCGTCATAATATGGGTTTTATGGTCC,CTTTTTCTGCTATTCTTGATCAAATGGCTC,131,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.404580,2908.694988,1641.233277,9051.396525,1550.709719,0.310717,1.067138,0.095022,0.127726,4.436039,4.694294,1.501069,0.821050
5,chr11,5291785,5291977,TTGTTCGTCATAATATGGGTTTTATGGTCC,TATTAGCAGAGTTATCTGTACTGTTGGCAT,192,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.380208,2798.177882,1591.162930,9484.503885,1398.947536,0.310717,2.072820,0.095022,0.171206,4.436039,4.668159,1.501069,5.302694
6,chr11,5291785,5291921,TTGTTCGTCATAATATGGGTTTTATGGTCC,CATTTGATCAAGAATAGCAGAAAAAGGAAA,136,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.397059,2919.839088,1657.720258,9140.680662,1541.707365,0.310717,1.555380,0.095022,0.148835,4.436039,5.386485,1.501069,1.345080
7,chr11,5291785,5291874,TTGTTCGTCATAATATGGGTTTTATGGTCC,CCTCTCATTTCTCCTGCCTTCACTTGGACG,89,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.359551,2720.374678,1489.370317,8477.729842,1586.816715,0.310717,4.816311,0.095022,0.289820,4.436039,4.104828,1.501069,2.803197
8,chr11,5291785,5291878,TTGTTCGTCATAATATGGGTTTTATGGTCC,CCAAGTGAAGGCAGGAGAAATGAGAGGAGC,93,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.365591,2739.000882,1508.226901,8540.033365,1594.701282,0.310717,3.426514,0.095022,0.229733,4.436039,4.590818,1.501069,8.542208
9,chr11,5291785,5291891,TTGTTCGTCATAATATGGGTTTTATGGTCC,GGAGAAATGAGAGGAGCAAGAAAGAGGAGC,106,CATAAAACCCATATTATGACGAACAACATTAGGATAAGTCCATATC...,0.386792,2806.353851,1561.282080,8739.053723,1589.887169,0.310717,1.375353,0.095022,0.141052,4.436039,4.380733,1.501069,7.168998

## HyenaDNA Prediction

In [20]:
import utils.HyenaDNA_main as Hyena

Loaded pretrained weights ok!

In [21]:
test_data['DeepSpCas9_harmony'] = 1/(1/(test_data['DeepSpCas9_s1']+1)+1/(test_data['DeepSpCas9_s2']+1))
test_data['DeepCRISPR_harmony'] = 1/(1/(test_data['DeepCRISPR_s1']+1)+1/(test_data['DeepCRISPR_s2']+1))
test_data['CRISPRedict_harmony']= 1/(1/(test_data['CRISPRedit_s1']+1)+1/(test_data['CRISPRedit_s2']+1))
test_data['Ruleset2_harmony']   = 1/(1/(test_data['Ruleset2_s1']+1)+1/(test_data['Ruleset2_s2']+1))
test_data = test_data.sort_values(
    by=['DeepSpCas9_harmony','DeepCRISPR_harmony','CRISPRedict_harmony','Ruleset2_harmony','DNase','ATAC','H3K27ac','H3K4me3'],
    ascending=False
)
test_data['hyena_score']=np.array([Hyena.hyena_inference(s[:16384]) for s in list(test_data['Median_sequence'].fillna('N'))])

In [22]:
(
test_data
.drop(['DeepSpCas9_s1','DeepSpCas9_s2','DeepCRISPR_s1','DeepCRISPR_s2',
       'CRISPRedit_s1','CRISPRedit_s2','Ruleset2_s1','Ruleset2_s2'],axis=1)
).to_csv('data/test_data_annot.csv',index=False)

In [23]:
test_data.head(n=10)

,chr,start,end,seq1,seq2,length,Median_sequence,GC,DNase,ATAC,...,DeepCRISPR_s2,Ruleset2_s1,Ruleset2_s2,CRISPRedit_s1,CRISPRedit_s2,DeepSpCas9_harmony,DeepCRISPR_harmony,CRISPRedict_harmony,Ruleset2_harmony,hyena_score
950,chr11,5290788,5290939,GTTATATACTAGCTATGTAACCTGTGGATA,GAAAGGATTCATAGCAGACAGCTAAGGCTG,151,CACAGGTTACATAGCTAGTATATAACTGAGAAATAATTTTATTTAT...,0.291391,1900.022724,440.597403,...,0.409091,4.343277,5.682983,7.878394e+00,5.614655,4.818646,0.729816,3.790572,2.969255,1.692340
550,chr11,5290315,5290408,CTTAGCTTAATTGTGAGGCTGATTTGGGGC,TATCACAATAGGGTCATGTTCAGTAGGGTG,93,CTTAATTGTGAGGCTGATTTGGGGCATAGCACCCCATCCTCTCTGT...,0.354839,3700.342380,1632.368994,...,0.411256,6.345100,7.117112,0.000000e+00,3.742232,4.410501,0.709935,0.825852,3.855917,-2.456371
91,chr11,5290939,5291023,GAAAGGATTCATAGCAGACAGCTAAGGCTG,AGATAGGGTAAGAGACAGGGAAGGAGGTGT,84,CTTAGCTGTCTGCTATGAATCCTTTCAAAATATACTTCTGAGAAAT...,0.392857,3630.333120,2072.854680,...,0.412841,5.682983,4.921576,5.614655e+00,7.078258,4.309074,0.705482,3.636780,3.139641,3.222538
954,chr11,5290788,5290983,GTTATATACTAGCTATGTAACCTGTGGATA,GAGAAATGAGAGAGAGAAATGGGGAGGGTA,195,CACAGGTTACATAGCTAGTATATAACTGAGAAATAATTTTATTTAT...,0.302564,2290.052242,781.030536,...,0.338000,4.343277,4.134341,7.878394e+00,4.650889,4.251791,0.710270,3.453083,2.618363,1.720539
125,chr11,5290272,5290408,TTGCAGGGTAGTGTAGGGACCACAGGGTTA,TATCACAATAGGGTCATGTTCAGTAGGGTG,136,CCTGTGGTCCCTACACTACCCTGCAAGACTCTTAGCTGCTTAGCTT...,0.411765,4124.267928,2053.887978,...,0.411256,4.524377,7.117112,8.389550e+00,3.742232,4.221795,0.701765,3.150871,3.287177,-5.961335
864,chr11,5290353,5290408,TTATGAGGATGTTGAAAGACAGAGAGGATG,TATCACAATAGGGTCATGTTCAGTAGGGTG,55,CTCTCTGTCTTTCAACATCCTCATAATAACTTGAGAATAATTTTAT...,0.254545,3041.935256,958.735147,...,0.411256,6.262190,7.117112,6.947796e+00,3.742232,4.193403,0.700580,2.970072,3.832945,2.422624
129,chr11,5290272,5290353,TTGCAGGGTAGTGTAGGGACCACAGGGTTA,TTATGAGGATGTTGAAAGACAGAGAGGATG,81,CCTGTGGTCCCTACACTACCCTGCAAGACTCTTAGCTGCTTAGCTT...,0.518519,4859.185174,2797.510272,...,0.391207,4.524377,6.262190,8.389550e+00,6.947796,4.107557,0.696772,4.304363,3.137596,-7.218352
861,chr11,5290347,5290408,GGATGTTGAAAGACAGAGAGGATGGGGTGC,TATCACAATAGGGTCATGTTCAGTAGGGTG,61,CCCATCCTCTCTGTCTTTCAACATCCTCATAATAACTTGAGAATAA...,0.295082,3150.548518,1075.756471,...,0.411256,4.317241,7.117112,7.172610e+00,3.742232,4.104718,0.696951,3.000921,3.212707,-3.093853
549,chr11,5290315,5290409,CTTAGCTTAATTGTGAGGCTGATTTGGGGC,ATCACAATAGGGTCATGTTCAGTAGGGTGA,94,CTTAATTGTGAGGCTGATTTGGGGCATAGCACCCCATCCTCTCTGT...,0.361702,3680.235529,1620.460186,...,0.362861,6.345100,6.526404,2.905930e-07,4.680868,4.097989,0.697476,0.850319,3.717323,-2.443855
731,chr11,5291272,5291400,TTATCAGGAGATATATTAGGAAAAAGGGAA,TGTGGAGCTAATGGTCCAAGATGGTGGAGC,128,AGGAGATATATTAGGAAAAAGGGAAACTGGAGAAACTGGGAGGAGT...,0.492188,32598.145680,5684.743856,...,0.361584,5.738492,4.271563,1.243406e+00,7.227676,4.086997,0.697033,1.762761,2.957720,5.492596